### ISSUE TITLE
Doesn't convert margin

### ISSUE THREAD

**Issue by dzearing** [kentcdodds/rtl-css-js#10]
I see padding coverted in the tests but not margin. `margin: 0 0 0 1px;` should autoflip. Seems to be missing.

**Comment by kentcdodds** [comment]
Hmmmmm, it should. Could you dig deeper to figure out what's going on? Thanks for bringing this up!

**Comment by dzearing** [comment]
I see:

```js
padding(value) {
    if (isNumber(value)) {
      return value
    }
    return handleQuartetValues(value)
  },
```

but nothing for margin in there. If you just search for `margin` you'll only find marginLeft/Right covered. Am I not seeing it?

**Comment by kentcdodds** [comment]
You're probably right. Could you [make a pull request] (http://makeapullrequest.com) to fix that? Thanks again!

**Comment by dzearing** [comment]
@kentcdodds Thank you for this library, glad we can help! :) @christiango submitted the PR to address.

**Comment by kentcdodds** [comment]
Thanks!
