### ISSUE TITLE
Doesn't handle `null` or `undefined`style values

### ISSUE THREAD

**Issue by majapw** [kentcdodds/rtl-css-js#13]
I have the following code in my app:
```
import rtlCSSJS from 'rtl-css-js';

const rtlStyles = rtlCSSJS({
  border: null,
  marginLeft: 16px,
  ...
});
```

The basic idea is that I can't super control the styles that are being passed in and sometimes have a `null` value for a specific style type. I would expect this to be parsed, but instead it fails pretty dramatically:
```
Cannot convert undefined or null to object
TypeError: Cannot convert undefined or null to object
    at keys (<anonymous>)
    at Function.keys (webpack:///./~/es5-shim/es5-shim.js?:1103:24)
    at convert (webpack:///./~/rtl-css-js/dist/index.js?:129:17)
    at getValueDoppelganger (webpack:///./~/rtl-css-js/dist/index.js?:176:12)
    at convertProperty (webpack:///./~/rtl-css-js/dist/index.js?:154:42)
    at eval (webpack:///./~/rtl-css-js/dist/index.js?:136:28)
    at Array.reduce (<anonymous>)
    at convert (webpack:///./~/rtl-css-js/dist/index.js?:129:30)
```

So digging into the source code, what's actually happening is that in order to recurse into the styles object, we check the value type here - https://github.com/kentcdodds/rtl-css-js/blob/master/src/index.js#L259-L261. 

Unfortunately, the `isObject` method (https://github.com/kentcdodds/rtl-css-js/blob/master/src/index.js#L259-L261) just checks for `typeof val === 'object'`, something that's true for `null` (yay javascript!). 

A simple patch would be to change `isObject` to return `val && typeof val === 'object'`. I can make a PR for that if you'd like! :)

**Comment by kentcdodds** [comment]
Happy to accept a PR to support this :+1: Thank you so much!

**Comment by kentcdodds** [comment]
This will be autoreleased momentarily.

**Comment by majapw** [comment]
Thanks so much!
