### ISSUE TITLE
Provide an option to pass back resets for styles

### ISSUE THREAD

**Issue by majapw** [kentcdodds/rtl-css-js#16]
Hello @kentcdodds!

For our particular usecase, we don't have access to whether or not we are in the RTL or the LTR context when we call this package. We are instead using `rtl-css-js` to generate flipped styles and resets that get applied at the same time as the original styles. You can see the code here - https://github.com/airbnb/react-with-styles-interface-aphrodite/blob/master/src/generateRTLStyles.js

The actual generated css down the line is something like:
```
[dir="rtl"] .inlineStyles_8vmhww {
    margin-right: 16px !important;
    margin-left: initial !important;
}

.inlineStyles_8vmhww {
    margin-left: 16px !important;
}
```

While we're currently resetting things to `initial`, we realized that there might be some benefit to having a specific reset value for different styles keys (also `initial` is bad in general because it doesn't seem to be a thing in IE).  

We were thinking this might be a good thing to build into `rtl-css-js` itself as an option so that you could do something like:
```
import rtlCSSJS from 'rtl-css-js';

const styles =  { left: 10 };
const flippedStyles = rtlCSSJS(styles, { withResets: true });
```
and then `rtl-css-js` could be responsible for choosing the best possible value. I was wondering if this would be something you would be willing to support.

@yzimet @lencioni

**Comment by kentcdodds** [comment]
Hmmm... Sorry, I'm not entirely sure I understand the use case. Could you clarify it a little for me please?
