### ISSUE TITLE
Implement the code changes to make all the skipped tests pass

### ISSUE THREAD

**Issue by kentcdodds** [kentcdodds/rtl-css-js#2]
This issue depends on #1 :)

Just take one test at a time and make it pass. TDD style 😎

**Comment by xymostech** [comment]
Awesome! Looks like you got these tests from cssjanus? I'd love to take a crack at some of these at some point...

**Comment by kentcdodds** [comment]
Yup! I got them straight from CSSJanus. Sure you can help! I've already started implementing them. I'll let you know when I'm done (and have pushed my changes), then you can try them out.

**Comment by kentcdodds** [comment]
@xymostech, you wanna give this PR a look? I'll add you as a collaborator if you want :) https://github.com/kentcdodds/rtl-css-js/pull/4
