### ISSUE TITLE
Tests for "undefined" values don't seem to run 

### ISSUE THREAD

**Issue by TxHawks** [kentcdodds/rtl-css-js#23]
- `rtl-css-js` version: 1.4.0
- `node` version: 8.4.0
- `npm` (or `yarn`) version: yarn 1.0.2 and npm 5.4.1

What you did:
`yarn test`
then `t` to filter and type `undefined`

What happened:
No tests are run, despite the fact that several matching the filter exist.

Problem description:
Tests that include an `undefined` value seem to not be running at all.

Suggested solution:
Not sure, but happy to try and fix if pointed in the right direction

**Comment by kentcdodds** [comment]
Hmmm... That sounds like an issue with jest. Could you reproduce this issue in a minimal reproduction repository?

**Comment by TxHawks** [comment]
How minimal do you want it to be? just a generic installation of Jest running a test that includes `undefined` as a value?

**Comment by kentcdodds** [comment]
As minimal as possible. I'm not at my computer right now so I haven't tried. The more minimal, the easier it will be to identify what the problem and solution will be.
