### ISSUE TITLE
Array.Includes is not supported on IE11

### ISSUE THREAD

**Issue by MarkFalconbridge** [kentcdodds/rtl-css-js#27]
- `rtl-css-js` version: 1.4.3
- `node` version:
- `npm` (or `yarn`) version:

Problem description:

When using rtl-css-js in Internet Explorer 11, line 59 of index.js (https://github.com/kentcdodds/rtl-css-js/blob/master/src/index.js#L59) throws the following exception:

TypeError: Object doesn't support property or method 'includes'

This is because IE doesn't support array.includes (https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/includes)

Suggested solution:

I'm currently working around this by using a polyfill but it could easily be solved using indexOf rather than includes on line 59.

**Comment by TxHawks** [comment]
My bad. Wasn't aware it won't be transpiled in the build process. Will send a PR that fixes this in an hour or so

**Comment by TxHawks** [comment]
This should be fixed as soon as @kentcdodds merges #28 

Sorry for this

**Comment by kentcdodds** [comment]
No worries. Thanks @TxHawks!
