### ISSUE TITLE
Support `transition`

### ISSUE THREAD

**Issue by milesj** [kentcdodds/rtl-css-js#39]
- `rtl-css-js` version: 1.11.0
- `node` version: 10.14.0
- `npm` (or `yarn`) version: 1.15.2

Relevant code or config

```javascript
{
  toggle: {
    left: 0,
    transition: 'left 300ms, transform: 300ms',
  },

  toggle_checked: {
    left: '100%',
    transform: 'translateX(-100%)',
  },
}

// This converts to
{
  toggle: {
    right: 0,
    transition: 'left 300ms, transform: 300ms',
  },

  toggle_checked: {
    right: '100%',
    transform: 'translateX(100%)',
  },
},
```

What you did:

^^ Above.

What happened:

Since transition does not convert properties, it causes broken animations.

Reproduction repository:

https://github.com/airbnb/lunar/pull/59

Problem description:

The `left` in transition does not convert to `right`, while the `left` property itself does. This obviously causes broken animations. For the time being I solved it with:

```
transition: 'left 300ms, right 300ms, transform: 300ms',
```

Suggested solution:

Convert properties within a `transition` statement.

**Comment by kentcdodds** [comment]
PR welcome 👍

**Comment by kentcdodds** [comment]
Sorry for being so terse. I should've waited to respond until I had more time. This makes sense to me and I'd welcome a pull request for it 👍
