### ISSUE TITLE
Building the repo gives `Definition for rule 'no-import-assign' was not found  no-import-assign` errors

### ISSUE THREAD

**Issue by RoystonS** [kentcdodds/rtl-css-js#48]
- `rtl-css-js` version: latest code (https://github.com/kentcdodds/rtl-css-js/commit/56d18ab9de6dc2cbb396676403ee558f72d49410)
- `node` version:  10.13.0
- `npm` (or `yarn`) version: 6.4.1

Relevant code or config:

Follow the steps in `CONTRIBUTING.md`:

1. Clone repo
2. `npm install`
3. `npm run validate`

OR

submit a PR and see the Travis build fail.

The error:
```
/home/travis/build/kentcdodds/rtl-css-js/core.esm.js
[lint]   1:1  error  Definition for rule 'no-import-assign' was not found  no-import-assign
```

Looks like we have an `eslint` configuration that doesn't match the version of `eslint`.

There's neither a yarn nor an npm lock file in this repo so it will float to latest deps on install.

Reproduction repository:
_This_ repo. ;-)

Suggested solution:
Some sort of dependencies update - I can't quite tell which bits are inside `kcd-scripts` and which bits aren't, at a cursory glance.

**Comment by kentcdodds** [comment]
Fixed! I updated all deps.
