### ISSUE TITLE
Computed properties not working

### ISSUE THREAD

**Issue by guilleasz** [kentcdodds/rtl-css-js#53]
Expected behavior:

The rtl function should switch the styles.

Describe the bug:

The rtl funcion doesn't switch all the styles.

```
const useStyles = createUseStyles({
  myButton1: {
    paddingLeft: "16px" ✅
  },
  myButton2: {
    paddingRight: ({ isMobile }) => (isMobile ? 0 : "26px") ❌
  },
  myLabel: props => ({
    paddingRight: "8px" ✅
  })
});
```

Codesandbox link:

https://codesandbox.io/s/react-jss-playground-37lqs

**Comment by kentcdodds** [comment]
Hi @guilleasz,

This looks like a bug with `jss-rtl`. We don't do anything with this stuff. Could you open an issue there instead?
